Repository NitinNair89/TheHungryRecipesHTML, pull requests merged in 2019-10, with the labels that each got.

#3 Fixes some recipes not being displayed
  app.js
Labels: enhancement

#12 Add Recipe Category Navbar
  app.js
  index.html
Labels: work in progress

#8 Add cache mechanism
  app.js
Labels: work in progress

#38 Updated about section, added GitHub Shields
  index.html
Labels: enhancement, hacktoberfest
